name: Build and publish lacells website
on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 2 * * 1

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download and split
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./lacells-creator -d -i -m -e -q
      - name: Prepare website
        run: |
          mkdir -p lacells.git
          cd lacells.git
          git init -q
          git config user.email lacells
          git config user.name lacells
          git remote add origin git@github.com:wvengen/lacells.git
      - name: Publish website
        env:
          LACELLS_GIT_SSH_KEY: ${{ secrets.LACELLS_GIT_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh && chmod 0700 ~/.ssh
          echo "$LACELLS_GIT_SSH_KEY" >~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
          GIT_PUSH_ARGS="--set-upstream origin master" ./misc/upload-git
